=== dbunibas/IQ-Meter/spicyBenchmark/misc/resources/datasources/mondial/city_Set.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="city_Set">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" name="city" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="population" nillable="false">
                <xs:complexType mixed="true">
                  <xs:sequence/>
                  <xs:attribute name="year" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="located_at" nillable="false">
                <xs:complexType>
                  <xs:sequence/>
                  <xs:attribute name="watertype" type="xs:string"/>
                  <xs:attribute name="water" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="country" type="xs:string"/>
            <xs:attribute name="province" type="xs:string"/>
            <xs:attribute name="longitude" type="xs:string"/>
            <xs:attribute name="latitude" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="key1">
      <xs:selector xpath=".//city"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
</xs:schema>

=== dbunibas/IQ-Meter/spicyBenchmark/misc/resources/datasources/mondial/city_Set-expectedInstance.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<city_Set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="city_Set.xsd">
  <city country="cid-cia-Albania" id="cty-cid-cia-Albania-Tirane" latitude="46.2" longitude="10.7" name="Tirane">
    <population year="87">192000</population>
  </city>
  <city country="cid-cia-Greece" id="cty-Greece-Athens" latitude="37.9667" longitude="23.7167" name="Athens" province="prov-cid-cia-Greece-3">
    <population year="81">885737</population>
    <located_at water="sea-Mittelmeer" watertype="sea"/>
  </city>
  <city country="cid-cia-Macedonia" id="cty-cid-cia-Macedonia-Skopje" name="Skopje"/>
  <city country="cid-cia-Serbia-and-Montenegro" id="cty-cid-cia-Serbia-and-Montenegro-Belgrade" latitude="44.8" longitude="20.4667" name="Belgrade">
    <population year="87">1407073</population>
  </city>
</city_Set>
