=== dbunibas/IQ-Meter/spicyBenchmark/misc/resources/datasources/statDB/statDB.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="statDB">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" name="cityStat" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" name="city" nillable="true" type="xs:string"/>
              <xs:element minOccurs="1" name="organizations" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="organization" nillable="false">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="1" name="companyId" nillable="true" type="xs:string"/>
                          <xs:element minOccurs="1" name="companyName" nillable="true" type="xs:string"/>
                          <xs:element minOccurs="1" name="fundings" nillable="false">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" minOccurs="1" name="fund" nillable="false">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element minOccurs="1" name="principalInvestigator" nillable="true" type="xs:string"/>
                                      <xs:element minOccurs="1" name="financialIdRef" nillable="true" type="xs:string"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="1" name="financials" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="financial" nillable="false">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="1" name="financialId" nillable="true" type="xs:string"/>
                          <xs:element minOccurs="1" name="amount" nillable="true" type="xs:string"/>
                          <xs:element minOccurs="1" name="project" nillable="true" type="xs:string"/>
                          <xs:element minOccurs="1" name="year" nillable="true" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="key1">
      <xs:selector xpath="./cityStat/financials/financial"/>
      <xs:field xpath="financialId"/>
    </xs:key>
    <xs:keyref name="keyRef1" refer="key1">
      <xs:selector xpath=".//fund"/>
      <xs:field xpath="financialIdRef"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== dbunibas/IQ-Meter/spicyBenchmark/misc/resources/datasources/statDB/statDB_expectedInstance.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<statDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="statDB.xsd">
    <cityStat>
        <city>New York</city>
        <organizations>
            <organization>
                <companyId>1</companyId>
                <companyName>IBM</companyName>
                <fundings>
                    <fund>
                        <principalInvestigator>Frank Miller</principalInvestigator>
                        <financialIdRef>101</financialIdRef>
                    </fund>
                    <fund>
                        <principalInvestigator>Neal Adams</principalInvestigator>
                        <financialIdRef>102</financialIdRef>
                    </fund>
                </fundings>
            </organization>
        </organizations>
        <financials>
            <financial>
                <financialId>101</financialId>
                <amount>1000.0</amount>
                <project>Clio</project>
                <year>2000</year>
            </financial>
            <financial>
                <financialId>102</financialId>
                <amount>5000.0</amount>
                <project>DB2</project>
                <year>1980</year>
            </financial>
        </financials>
    </cityStat>
    <cityStat>
        <city>Seattle</city>
        <organizations>
            <organization>
                <companyId>2</companyId>
                <companyName>Microsoft</companyName>
                <fundings>
                    <fund>
                        <principalInvestigator>Stan Lee</principalInvestigator>
                        <financialIdRef>103</financialIdRef>
                    </fund>
                </fundings>
            </organization>
            <organization>
                <companyId>3</companyId>
                <companyName>Boing</companyName>
                <fundings>
                    <fund>
                        <principalInvestigator>Steve Ditko</principalInvestigator>
                        <financialIdRef>104</financialIdRef>
                    </fund>
                </fundings>
            </organization>
        </organizations>
        <financials>
            <financial>
                <financialId>103</financialId>
                <amount>1000.0</amount>
                <project>SQL Server</project>
                <year>1980</year>
            </financial>
            <financial>
                <financialId>104</financialId>
                <amount>1500.0</amount>
                <project>B530</project>
                <year>2006</year>
            </financial>
            <financial>
                <financialId>101</financialId>
                <amount>2000.0</amount>
                <project>Dummy Financial</project>
                <year>2006</year>
            </financial>
        </financials>
    </cityStat>
</statDB>
